grails-app/controllers/org/opentele/server/provider/model/questionnaire/QuestionnaireController.groovy
package org.opentele.server.provider.model.questionnaire

import grails.plugin.springsecurity.annotation.Secured
import org.opentele.server.core.model.types.PermissionName
import org.opentele.server.model.Clinician
import org.opentele.server.model.patientquestionnaire.CompletedQuestionnaire
import org.opentele.server.model.patientquestionnaire.NodeResult
import org.springframework.dao.DataIntegrityViolationException
import org.opentele.server.model.questionnaire.Questionnaire

@Secured(PermissionName.NONE)
class QuestionnaireController {
	def questionnaireService
    def springSecurityService
    def patientService
    def acknowledgeQuestionnaireService
    def clinicianService

    @Secured(PermissionName.QUESTIONNAIRE_READ_ALL)
	def index() {
        redirect(controller: "questionnaireHeader", action: "list", params: params)
	}
    @Secured(PermissionName.QUESTIONNAIRE_READ_ALL)
	def list() {
        redirect(controller: "questionnaireHeader", action: "list", params: params)
	}

	/**
	 * Acknowledges a questionnaire. The function checks, if the user has the sufficient rights. The result is redirected back to the overview.
     * If params.withAutoMessage is set, the questionnaire is marked with a showAcknowledgementToPatient flag.
	 */
    @Secured(PermissionName.QUESTIONNAIRE_ACKNOWLEDGE)
	def acknowledge() {
		def qId = params.id
		def note = params.note
        def withAutoMessage = (params.withAutoMessage != null && params.withAutoMessage.equals('true'))
		def questionnaire = CompletedQuestionnaire.get(qId)
		boolean errorOccured = false

        acknowledgeQuestionnaireService.acknowledge(questionnaire, note, withAutoMessage)

		if (questionnaire.hasErrors()) {
			def msg
			questionnaire.errors.each { error ->
				msg = msg + error
				errorOccured = true
			}
			flash.error = msg
		} else {
			flash.message  = g.message(code: "completedQuestionnaire.acknowledged", args: [questionnaire.patientQuestionnaire?.name, g.formatDate(date: questionnaire.acknowledgedDate)])
		}

        def lastReferer = session.getAttribute('lastReferer')
        if (lastReferer) {
            session.removeAttribute('lastReferer')
            redirect(url: lastReferer)
        }
	}

    @Secured(PermissionName.QUESTIONNAIRE_CREATE)
	def create() {
		[questionnaireInstance: new Questionnaire(params)]
	}

    @Secured(PermissionName.QUESTIONNAIRE_CREATE)
	def save() {
		def questionnaireInstance = new Questionnaire(params)
		if (!questionnaireInstance.save(flush: true)) {
			render(view: "create", model: [questionnaireInstance: questionnaireInstance])
			return
		}

		flash.message = message(code: 'default.created.message', args: [message(code: 'questionnaire.label', default: 'Questionnaire')])
		redirect(action: "show", id: questionnaireInstance.id)
	}

    @Secured(PermissionName.QUESTIONNAIRE_READ)
	def show() {
		def questionnaireInstance = Questionnaire.get(params.id)
		if (!questionnaireInstance) {
			flash.message = message(code: 'default.not.found.message', args: [message(code: 'questionnaire.label', default: 'Questionnaire')])
			redirect(action: "list")
			return
		}

		[questionnaireInstance: questionnaireInstance]
	}

    @Secured(PermissionName.QUESTIONNAIRE_WRITE)
	def edit() {
		def questionnaireInstance = Questionnaire.get(params.id)
		if (!questionnaireInstance) {
			flash.message = message(code: 'default.not.found.message', args: [message(code: 'questionnaire.label', default: 'Questionnaire')])
			redirect(action: "list")
			return
		}

		[questionnaireInstance: questionnaireInstance]
	}

    @Secured(PermissionName.QUESTIONNAIRE_WRITE)
	def update() {
		def questionnaireInstance = Questionnaire.get(params.id)
		if (!questionnaireInstance) {
			flash.message = message(code: 'default.not.found.message', args: [message(code: 'questionnaire.label', default: 'Questionnaire')])
			redirect(action: "list")
			return
		}

		if (params.version) {
			def version = params.version.toLong()
			if (questionnaireInstance.version > version) {
				questionnaireInstance.errors.rejectValue("version", "default.optimistic.locking.failure",
						[message(code: 'questionnaire.label', default: 'Questionnaire')] as Object[],
						"Another user has updated this Questionnaire while you were editing")
				render(view: "edit", model: [questionnaireInstance: questionnaireInstance])
				return
			}
		}

		questionnaireInstance.properties = params

		if (!questionnaireInstance.save(flush: true)) {
			render(view: "edit", model: [questionnaireInstance: questionnaireInstance])
			return
		}

		flash.message = message(code: 'default.updated.message', args: [message(code: 'questionnaire.label', default: 'Questionnaire')])
		redirect(action: "show", id: questionnaireInstance.id)
	}

    @Secured(PermissionName.QUESTIONNAIRE_DELETE)
	def delete() {
		def questionnaireInstance = Questionnaire.get(params.id)
		if (!questionnaireInstance) {
			flash.message = message(code: 'default.not.found.message', args: [message(code: 'questionnaire.label', default: 'Questionnaire')])
			redirect(action: "list")
			return
		}

		try {
			questionnaireInstance.delete(flush: true)
			flash.message = message(code: 'default.deleted.message', args: [message(code: 'questionnaire.label', default: 'Questionnaire')])
			redirect(action: "list")
		}
		catch (DataIntegrityViolationException e) {
			flash.message = message(code: 'default.not.deleted.message', args: [message(code: 'questionnaire.label', default: 'Questionnaire')])
			redirect(action: "show", id: params.id)
		}
	}

    @Secured(PermissionName.QUESTIONNAIRE_IGNORE)
	def toggleIgnoreQuestionnaire() {
		def completedQuestionnaire = CompletedQuestionnaire.get(params.id)
		def user = springSecurityService.currentUser
		def clinician = Clinician.findByUser(user)
		def reason = params.ignoreReason
		
		if (!completedQuestionnaire._questionnaireIgnored) {
			completedQuestionnaire._questionnaireIgnored = true
			completedQuestionnaire.questionnaireIgnoredReason = reason
			completedQuestionnaire.questionnareIgnoredBy = clinician
			completedQuestionnaire.save()
			completedQuestionnaire.completedQuestions.each {nodeResult ->
				nodeResult.setNodeIgnored(true)
				nodeResult.setNodeIgnoredBy(clinician)
				nodeResult.setNodeIgnoredReason(reason)
				nodeResult.save()
			}
		} else {
			completedQuestionnaire._questionnaireIgnored = false
			completedQuestionnaire.questionnaireIgnoredReason = null
			completedQuestionnaire.questionnareIgnoredBy = null
			completedQuestionnaire.save()
			completedQuestionnaire.completedQuestions.each {nodeResult ->
				nodeResult.setNodeIgnored(false)
				nodeResult.setNodeIgnoredBy(null)
				nodeResult.setNodeIgnoredReason(null)
				nodeResult.save()
			}
		}
		
		completedQuestionnaire.save()
        redirect(controller: "patient", action: "questionnaire", params: [
                id: params.id, ignoreNavigation: 'true', note: params.note])
	}

    @Secured(PermissionName.NODE_RESULT_IGNORE)
	def toggleIgnoreNode() {
		def node = NodeResult.find("from NodeResult as node where node.id=(:nID)", [nID:Long.parseLong(params.resultID)])

		if (node?.nodeIgnored) {
			//If we un-ignore atleast one node, the entire questionnaire cannot be ignored
			node?.completedQuestionnaire._questionnaireIgnored = false
			node?.completedQuestionnaire.questionnaireIgnoredReason = null
			node?.completedQuestionnaire.questionnareIgnoredBy = null

			node.setNodeIgnored(false)
			node.setNodeIgnoredBy(null)
			node.setNodeIgnoredReason(null)
		} else {
			def user = springSecurityService.currentUser
			def clinician = Clinician.findByUser(user)
			node?.setNodeIgnored(true)
			node?.setNodeIgnoredBy(clinician)
			node?.setNodeIgnoredReason(params.ignoreNodeReason)
		}
		node?.save()
	}


}

grails-app/controllers/org/opentele/server/provider/model/questionnaire/QuestionnaireEditorController.groovy
package org.opentele.server.provider.model.questionnaire
import dk.silverbullet.kih.api.auditlog.SkipAuditLog
import grails.converters.JSON
import grails.plugin.springsecurity.annotation.Secured
import org.codehaus.groovy.grails.web.json.JSONObject

import org.opentele.server.model.questionnaire.Questionnaire
import org.opentele.server.core.command.QuestionnaireEditorCommand
import org.opentele.server.model.questionnaire.QuestionnaireHeader
import org.opentele.server.core.model.types.PermissionName

@Secured(PermissionName.NONE)
class QuestionnaireEditorController {

    def questionnaireEditorService
    def clinicianService

    static allowedMethods = [save:'POST',  editorState:'GET']

    // Databinding with commandobject and JSON works because of org.opentele.server.JSONParamsMapFilters
    @Secured(PermissionName.QUESTIONNAIRE_CREATE)
    def save() {
        def editCommand = new QuestionnaireEditorCommand()
        bindData(editCommand, params)
        editCommand.cloneScheduleData(params.standardSchedule)

        if (editCommand.validate()) {
            try {
                questionnaireEditorService.createOrUpdateQuestionnaire(editCommand, clinicianService.currentClinician)
                render([editCommand.questionnaire.id] as JSON)
                return
            } catch (e) {
                log.warn("Could not save questionnaire due to error: ${e.message}", e)
                editCommand.errors.reject("questionnaireeditor.unknown.error")
            }
        } else {
            log.debug("Save validation failed")
        }

        response.status = 422
        render(template: '/questionnaireSchedule/errors', model: [errors: editCommand.errors])
    }

    @Secured(PermissionName.QUESTIONNAIRE_CREATE)
    def edit(Long id, QuestionnaireEditorCommand command) {
        def questionnaireHeader = QuestionnaireHeader.get(id)
        command.questionnaireHeader = questionnaireHeader
        command.title = questionnaireHeader.name
        bindData(command, command.questionnaire.standardSchedule.properties)

        if(command.validate(['questionnaireHeader.id'])) {
            command.properties
        } else {
            flash.message = message(code: 'default.not.found.message',
                    args: [message(code: 'questionnaireHeader.label',
                            default: 'QuestionnaireHeader'),
                           id])
            redirect(controller: "questionnaireHeader", action: "list")
        }
    }

    @Secured(PermissionName.QUESTIONNAIRE_WRITE)
    def editorState(Long baseId) {
        def questionnaire = Questionnaire.findById(baseId)
        render new JSONObject(questionnaire?.editorState) as JSON
    }

    @Secured(PermissionName.QUESTIONNAIRE_WRITE)
    @SkipAuditLog
    def keepAlive() {
        render "pong"
    }
}

grails-app/controllers/org/opentele/server/provider/model/questionnaire/QuestionnaireGroup2QuestionnaireHeaderController.groovy
package org.opentele.server.provider.model.questionnaire

import grails.plugin.springsecurity.annotation.Secured

import org.opentele.server.model.questionnaire.QuestionnaireGroup
import org.opentele.server.model.questionnaire.QuestionnaireGroup2QuestionnaireHeader
import org.opentele.server.core.model.types.PermissionName
import org.opentele.server.provider.command.QuestionnaireGroup2QuestionnaireHeaderCommand
import org.springframework.dao.DataIntegrityViolationException

@Secured(PermissionName.NONE)
class QuestionnaireGroup2QuestionnaireHeaderController {

    static allowedMethods = [save: "POST", update: "POST", delete: "POST"]
    def questionnaireService
    def questionnaireGroupService

    def index() {
        redirect(action: "list", params: params)
    }

    @Secured(PermissionName.QUESTIONNAIRE_GROUP_CREATE)
    def create(QuestionnaireGroup2QuestionnaireHeaderCommand command) {
        if (!command.selectableQuestionnaireHeaders) {
            flash.message = message(code: 'questionnaireGroup2QuestionnaireHeader.questionnaire.none.left')
            redirect(controller: "questionnaireGroup", action: "show", id: params.questionnaireGroup.id)
        } else {
            command.properties
        }
    }

    @Secured(PermissionName.QUESTIONNAIRE_GROUP_CREATE)
    def save(QuestionnaireGroup2QuestionnaireHeaderCommand command) {
        questionnaireGroupService.save(command)
        if (command.hasErrors()) {
            render(view: 'create', model: modelWithErrors(command))
        } else {
            flash.message = message(code: 'default.created.message', args: [message(code: 'questionnaireGroup2QuestionnaireHeader.label', default: 'QuestionnaireSchedule')])
            redirect(controller: "questionnaireGroup", action: "show", id: command.questionnaireGroup.id)
        }
    }


    @Secured(PermissionName.QUESTIONNAIRE_GROUP_WRITE)
    def edit(Long id, QuestionnaireGroup2QuestionnaireHeaderCommand command) {
        withInstance(id) { QuestionnaireGroup2QuestionnaireHeader questionnaireGroup2Header ->

            command.questionnaireGroup2QuestionnaireHeader = questionnaireGroup2Header
            command.questionnaireGroup = questionnaireGroup2Header.questionnaireGroup
            command.selectedQuestionnaireHeader = questionnaireGroup2Header.questionnaireHeader
            if(questionnaireGroup2Header?.standardSchedule?.type) {
                bindData(command,questionnaireGroup2Header.standardSchedule.properties)
            }
            def model = command.properties

            return model
        }

    }

    @Secured(PermissionName.QUESTIONNAIRE_GROUP_WRITE)
    def update(QuestionnaireGroup2QuestionnaireHeaderCommand command) {
        if(!command.questionnaireGroup2QuestionnaireHeader) {
            flash.message = message(code: 'default.not.found.message', args: [message(code: 'questionnaireGroup2QuestionnaireHeader.label', default: 'QuestionnaireGroup2QuestionnaireHeader'), "$id"])
            redirect(controller: "questionnaireGroup", action: "list")
            return
        }

        questionnaireGroupService.update(command)

        if (command.hasErrors()) {
            render(view: 'edit', model: modelWithErrors(command))
        } else {
            flash.message = message(code: 'default.updated.message', args: [message(code: 'questionnaireGroup2QuestionnaireHeader.label', default: 'QuestionnaireSchedule')])
            redirect(controller: "questionnaireGroup", action: "show", id: command.questionnaireGroup.id)
        }

    }

    @Secured(PermissionName.QUESTIONNAIRE_GROUP_DELETE)
    def delete(Long id) {
        withInstance(id) {
            QuestionnaireGroup questionnaireGroup = it.questionnaireGroup
            try {
                questionnaireGroup.removeFromQuestionnaireGroup2Header(it as QuestionnaireGroup2QuestionnaireHeader)
                questionnaireGroup.save()
                it.delete(flush: true)
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'questionnaireGroup2QuestionnaireHeader.label', default: 'QuestionnaireGroup2QuestionnaireHeader'), questionnaireGroup.id])
                redirect(controller: "questionnaireGroup", action: "show", id: questionnaireGroup.id)
            }
            catch (DataIntegrityViolationException ignored) {
                flash.message = message(code: 'default.not.deleted.message', args: [message(code: 'questionnaireGroup2QuestionnaireHeader.label', default: 'QuestionnaireGroup2QuestionnaireHeader'), questionnaireGroup.id])
                redirect(controller: "questionnaireGroup", action: "show", id: questionnaireGroup.id)
            }
        }
    }
    private modelWithErrors(QuestionnaireGroup2QuestionnaireHeaderCommand command) {
        def model = command.properties ? [*:command.properties, errors: command.errors] : [errors: command.errors]
        model
    }

    private withInstance(Long id, Closure closure) {
        def questionnaireGroup2Header = QuestionnaireGroup2QuestionnaireHeader.get(id)
        if (questionnaireGroup2Header) {
            return closure.call(questionnaireGroup2Header)
        } else {
            flash.message = message(code: 'default.not.found.message', args: [message(code: 'questionnaireGroup2QuestionnaireHeader.label', default: 'QuestionnaireGroup2QuestionnaireHeader'), "$id"])
            redirect(controller: "questionnaireGroup", action: "list")
        }

    }


}

grails-app/views/questionnaire/_form.gsp
<%@ page import="org.opentele.server.model.questionnaire.Questionnaire"%>



<div class="fieldcontain ${hasErrors(bean: questionnaireInstance, field: 'name', 'error')} ">
	<label for="name">
        <g:message code="questionnaire.name.label" default="Name" />
	</label>
	<g:textField name="name" value="${questionnaireInstance?.name}" />
</div>

<div
	class="fieldcontain ${hasErrors(bean: questionnaireInstance, field: 'revision', 'error')} ">
	<label for="revision">
        <g:message code="questionnaire.revision.label" default="Revision" />
	</label>
	<g:textField name="revision" value="${questionnaireInstance?.revision}" />
</div>

<div
	class="fieldcontain ${hasErrors(bean: questionnaireInstance, field: 'creator', 'error')} required">
	<label for="creator">
        <g:message code="questionnaire.creator.label" default="Creator" />
        <span class="required-indicator">*</span>
	</label>
	<g:select id="creator" name="creator.id"
		from="${org.opentele.server.model.Clinician.list()}" optionKey="id"
		required="" value="${questionnaireInstance?.creator?.id}"
		class="many-to-one" />
</div>

<div
	class="fieldcontain ${hasErrors(bean: questionnaireInstance, field: 'creationDate', 'error')} required">
	<label for="creationDate">
        <g:message code="questionnaire.creationDate.label" default="Creation Date" />
        <span class="required-indicator">*</span>
	</label>
    <jq:datePicker name="creationDate" precision="day" value="${questionnaireInstance?.creationDate}" />
</div>

grails-app/views/questionnaire/create.gsp
<%@ page import="org.opentele.server.model.questionnaire.Questionnaire"%>
<!doctype html>
<html>
<head>
<meta name="layout" content="main">
<g:set var="entityName" value="${message(code: 'questionnaire.label', default: 'Questionnaire')}" />
<title><g:message code="default.create.label" args="[entityName]" /></title>
</head>
<body>

	<div id="create-questionnaire" class="content scaffold-create"
		role="main">
		<h1>
			<g:message code="default.create.label" args="[entityName]" />
		</h1>
		<g:if test="${flash.message}">
			<div class="message" role="status">
				${flash.message}
			</div>
		</g:if>
		<g:hasErrors bean="${questionnaireInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${questionnaireInstance}" var="error">
					<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if> >
                        <g:message error="${error}" />
                    </li>
				</g:eachError>
			</ul>
		</g:hasErrors>
		<g:form action="save">
			<fieldset class="form">
				<g:render template="form" />
			</fieldset>
			<fieldset class="buttons">
				<g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label')}" />
			</fieldset>
		</g:form>
	</div>
</body>
</html>

grails-app/views/questionnaire/edit.gsp
<%@ page import="org.opentele.server.core.model.types.PermissionName; org.opentele.server.core.model.types.PermissionName; org.opentele.server.model.questionnaire.Questionnaire"%>
<!doctype html>
<html>
<head>
<meta name="layout" content="main">
<g:set var="entityName" value="${message(code: 'questionnaire.label', default: 'Questionnaire')}" />
<title><g:message code="default.edit" args="[entityName]" /></title>
</head>
<body>

	<div id="edit-questionnaire" class="content scaffold-edit" role="main">
		<h1>
			<g:message code="default.edit" args="[entityName]" />
		</h1>
		<g:if test="${flash.message}">
			<div class="message" role="status">
				${flash.message}
			</div>
		</g:if>
		<g:hasErrors bean="${questionnaireInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${questionnaireInstance}" var="error">
					<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if> >
                        <g:message error="${error}" />
                    </li>
				</g:eachError>
			</ul>
		</g:hasErrors>
        
		<g:form method="post">
			<g:hiddenField name="id" value="${questionnaireInstance?.id}" />
			<g:hiddenField name="version" value="${questionnaireInstance?.version}" />
			<fieldset class="form">
				<g:render template="form" />
			</fieldset>
			<fieldset class="buttons">
				<g:actionSubmit class="save" action="update" value="${message(code: 'default.update')}" />
                <sec:ifAnyGranted roles="${org.opentele.server.core.model.types.PermissionName.QUESTIONNAIRE_DELETE}">
                    <g:actionSubmit class="delete" action="delete"
                        value="${message(code: 'default.button.delete.label')}"
                        formnovalidate=""
                        onclick="return confirm('${message(code: 'default.button.delete.confirm.message')}');" />
                </sec:ifAnyGranted>
			</fieldset>
		</g:form>
	</div>
</body>
</html>

grails-app/views/questionnaire/list.gsp
<%@ page
	import="org.opentele.server.core.model.types.PermissionName; org.opentele.server.core.model.types.PermissionName; org.opentele.server.provider.constants.Constants; org.opentele.server.model.questionnaire.Questionnaire"%>
<!doctype html>
<html>
<head>
<meta name="layout" content="main">
<g:set var="entityName" value="${message(code: 'questionnaire.label', default: 'Questionnaire')}" />
<title><g:message code="default.list.label" args="[entityName]" /></title>
</head>
<body>
	<div id="list-questionnaire" class="content scaffold-list" role="main">
		<h1>
			<g:message code="default.list.label" args="[entityName]" />
		</h1>
		<g:if test="${flash.message}">
			<div class="message" role="status">
				${flash.message}
			</div>
		</g:if>
		<table>
			<thead>
				<tr>
					<g:sortableColumn property="name" title="${message(code: 'questionnaire.name.label', default: 'Name')}" />

					<g:sortableColumn property="revision" title="${message(code: 'questionnaire.revision.label', default: 'Revision')}" />

					<th>
                        <g:message code="questionnaire.creator.label" default="Creator" />
                    </th>

					<g:sortableColumn property="creationDate" title="${message(code: 'questionnaire.creationDate.label', default: 'Creation Date')}" />
				</tr>
			</thead>
			<tbody>
				<g:each in="${questionnaireInstanceList}" status="i" var="questionnaireInstance">
					<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
						<td>
                            <g:link action="show" id="${questionnaireInstance.id}">
								${fieldValue(bean: questionnaireInstance, field: "name")}
							</g:link>
                        </td>
						<td>
							${fieldValue(bean: questionnaireInstance, field: "revision")}
						</td>

						<td>
							${fieldValue(bean: questionnaireInstance, field: "creator")}
						</td>

						<td>
                            <g:formatDate date="${questionnaireInstance.creationDate}" />
                        </td>

					</tr>
				</g:each>
			</tbody>
		</table>
		<div class="pagination">
			<g:paginate total="${questionnaireInstanceTotal}" />
		</div>
        <sec:ifAnyGranted roles="${org.opentele.server.core.model.types.PermissionName.QUESTIONNAIRE_CREATE}">
        <fieldset class="buttons">
            <g:link class="create" controller="questionnaireEditor">
                <g:message code="default.create.label" args="${[g.message(code:'questionnaire.label')]}" />
            </g:link>
        </fieldset>
        </sec:ifAnyGranted>
	</div>
</body>
</html>

grails-app/views/questionnaire/show.gsp
<%@ page
	import="org.opentele.server.core.model.types.PermissionName; org.opentele.server.core.model.types.PermissionName; org.opentele.server.core.model.types.PermissionName; org.opentele.server.core.model.types.PermissionName; org.opentele.server.provider.constants.Constants; org.opentele.server.model.questionnaire.Questionnaire"%>
<!doctype html>
<html>
<head>
<meta name="layout" content="main">
<g:set var="entityName"
	value="${message(code: 'questionnaire.label', default: 'Questionnaire')}" />
<title><g:message code="default.show.label" args="[entityName]" /></title>
</head>
<body>

	<div id="show-questionnaire" class="content scaffold-show" role="main">
		<h1>
			<g:message code="default.show.label" args="[entityName]" />
		</h1>
		<g:if test="${flash.message}">
			<div class="message" role="status">
				${flash.message}
			</div>
		</g:if>
		<ol class="property-list questionnaire">

			<g:if test="${questionnaireInstance?.name}">
				<li class="fieldcontain">
                    <span id="name-label" class="property-label">
                    <g:message code="questionnaire.name.label" default="Name" />
                </span>
                    <span class="property-value" aria-labelledby="name-label">
                        <g:fieldValue bean="${questionnaireInstance}" field="name" />
                    </span>
                </li>
			</g:if>

			<g:if test="${questionnaireInstance?.revision}">
				<li class="fieldcontain">
                    <span id="revision-label" class="property-label">
                        <g:message code="questionnaire.revision.label" default="Revision" />
                    </span>
                    <span class="property-value" aria-labelledby="revision-label">
                        <g:fieldValue bean="${questionnaireInstance}" field="revision" />
                    </span>
                </li>
			</g:if>

			<g:if test="${questionnaireInstance?.creator}">
				<li class="fieldcontain">
                    <span id="creator-label" class="property-label">
                        <g:message code="questionnaire.creator.label" default="Creator" />
                    </span>
                    <span class="property-value" aria-labelledby="creator-label">
                        <g:link controller="clinician" action="show" id="${questionnaireInstance?.creator?.id}">
							${questionnaireInstance?.creator}
						</g:link>
                    </span>
                </li>
			</g:if>

			<g:if test="${questionnaireInstance?.creationDate}">
				<li class="fieldcontain">
                    <span id="creationDate-label" class="property-label">
                        <g:message code="questionnaire.creationDate.label" default="Creation Date" />
                    </span>

					<span class="property-value" aria-labelledby="creationDate-label">
                        <g:formatDate date="${questionnaireInstance?.creationDate}" />
                    </span>
                </li>
			</g:if>

			<g:if test="${questionnaireInstance?.questionnaire2MeterTypes}">
				<li class="fieldcontain">
                    <span id="questionnaire2MeterTypes-label" class="property-label">
                        <g:message code="questionnaire.questionnaire2MeterTypes.label"/>
                    </span>
                    <g:each in="${questionnaireInstance.questionnaire2MeterTypes}" var="q">
						<span class="property-value" aria-labelledby="questionnaire2MeterTypes-label">
                            <g:link controller="questionnaire2MeterType" action="show" id="${q.id}">
								${q}
							</g:link>
                        </span>
					</g:each>
                </li>
			</g:if>
		</ol>

			<g:form>
				<fieldset class="buttons">
					<g:hiddenField name="id" value="${questionnaireInstance?.id}" />

                    <sec:ifAnyGranted roles="${org.opentele.server.core.model.types.PermissionName.QUESTIONNAIRE_WRITE}">
                        <g:link class="edit" action="edit" id="${questionnaireInstance?.id}">
                            <g:message code="default.button.rename.label"/>
                        </g:link>
                    </sec:ifAnyGranted>

                    <sec:ifAnyGranted roles="${org.opentele.server.core.model.types.PermissionName.QUESTIONNAIRE_DELETE}">
                        <g:actionSubmit class="delete" action="delete"
                            value="${message(code: 'default.button.delete.label')}"
                            onclick="return confirm('${message(code: 'default.button.delete.confirm.message')}');" />
                    </sec:ifAnyGranted>

                    <g:if test="${questionnaireInstance?.editorState}">
                        <sec:ifAnyGranted roles="${org.opentele.server.core.model.types.PermissionName.QUESTIONNAIRE_WRITE}">
                            <g:link class="edit" controller="questionnaireEditor" action="show" id="${questionnaireInstance?.id}">
                                <g:message code="questionnaire.button.show.in.editor.label"/>
                            </g:link>
                        </sec:ifAnyGranted>
                    </g:if>
				</fieldset>
			</g:form>
	</div>
</body>
</html>